// Mocks generated by Mockito 5.4.2 from annotations
// in petdopter/test/data/data_sources/authentication_remote_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:petdopter/core/core.dart' as _i6;
import 'package:petdopter/domain/entities/user_entity.dart' as _i5;
import 'package:petdopter/domain/repository/auth_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepositroy].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepositroy extends _i1.Mock implements _i3.AuthRepositroy {
  @override
  _i4.Future<_i2.Either<_i5.UserEntity, _i6.Failure>> signInWithGmail() =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithGmail,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.UserEntity, _i6.Failure>>.value(
            _FakeEither_0<_i5.UserEntity, _i6.Failure>(
          this,
          Invocation.method(
            #signInWithGmail,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.UserEntity, _i6.Failure>>.value(
                _FakeEither_0<_i5.UserEntity, _i6.Failure>(
          this,
          Invocation.method(
            #signInWithGmail,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.UserEntity, _i6.Failure>>);
  @override
  _i4.Future<_i2.Either<bool, _i6.Failure>> loggOut() => (super.noSuchMethod(
        Invocation.method(
          #loggOut,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<bool, _i6.Failure>>.value(
            _FakeEither_0<bool, _i6.Failure>(
          this,
          Invocation.method(
            #loggOut,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<bool, _i6.Failure>>.value(
                _FakeEither_0<bool, _i6.Failure>(
          this,
          Invocation.method(
            #loggOut,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<bool, _i6.Failure>>);
}
