// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmj6bDqUwp3KaZAsv3FxDNmJb6lZSbLQU',
    appId: '1:1010380121613:web:7a58fc176487c1d288d744',
    messagingSenderId: '1010380121613',
    projectId: 'petdopter',
    authDomain: 'petdopter.firebaseapp.com',
    storageBucket: 'petdopter.appspot.com',
    measurementId: 'G-Z2GF2CEE1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn3B4wwodL8jl49wJuJkk05mZWq_rmA5c',
    appId: '1:1010380121613:android:c8eec6410f518c7f88d744',
    messagingSenderId: '1010380121613',
    projectId: 'petdopter',
    storageBucket: 'petdopter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIu_rP3hR3_YiZpDcBwTUs1_rBUdL_suc',
    appId: '1:1010380121613:ios:e69e9851be2d684b88d744',
    messagingSenderId: '1010380121613',
    projectId: 'petdopter',
    storageBucket: 'petdopter.appspot.com',
    androidClientId: '1010380121613-a9s08rbrap4bteh4j79bthacnc5tfave.apps.googleusercontent.com',
    iosClientId: '1010380121613-7irtdntjfk923mlu91kvas1vi9opd1sd.apps.googleusercontent.com',
    iosBundleId: 'com.petdopter.petdopter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIu_rP3hR3_YiZpDcBwTUs1_rBUdL_suc',
    appId: '1:1010380121613:ios:a155a363e51ec9f688d744',
    messagingSenderId: '1010380121613',
    projectId: 'petdopter',
    storageBucket: 'petdopter.appspot.com',
    androidClientId: '1010380121613-a9s08rbrap4bteh4j79bthacnc5tfave.apps.googleusercontent.com',
    iosClientId: '1010380121613-9875895q54jshckh4q4frpriec0insj2.apps.googleusercontent.com',
    iosBundleId: 'com.petdopter.petdopter.RunnerTests',
  );
}
